### ISSUE TITLE
[Request] config overhaul

### ISSUE THREAD

**Issue by supersaiyansubtlety** [yurisuika/Endemic#2]
The current config option seems unnecessarily limited.

I'd be happy to help implement either of my suggestions (using cloth config as an optional dependency) if you open-source the mod. 

My first suggestion:
- `enabled`: `true`/`false`; no change from existing config here
- `special_biome_generation`: `true`/`false`; If true, saplings grown their special biomes will grow into one of the special tree structures of that biome. If false, vanilla behavior in these biomes.
- `mismatched_biome_generation`: `NORMAL`/`STUNTED`/`DEAD`/`NONE`; for saplings in biomes where their trees don't generate: normal is like vanilla, stunted grows into small trees, dead becomes dead bush, none never changes
- `barren_biome_generation`: same options as mismatched_biome_generation; for biomes where *no* trees generate (desert, beach, ice spikes)
- `nether_generation`: same options as mismatched_biome_generation
- `end_generation`: same options as mismatched_biome_generation

Alternate suggestion (chances):
- `enabled`: true/false; no change from existing config here

- `specail_biome_generation_chance`: `float` [0, 1]; chance that saplings in their special biomes will generate into one of the special tree structures of that biome.

- `mismatched_biome_generation_stunted_chance`: `float` [0, 1]; chance that saplings in their mismatched biomes will generate into smaller trees
- `mismatched_biome_generation_dead_chance`: `float` [0, 1]; chance that saplings in their mismatched biomes will generate into dead bushes, only tried after `mismatched_biome_generation_stunted_chance` fails 

- `barren_biome_generation_stunted_chance`:  like `mismatched_biome_generation_stunted_chance` for barren biomes
- `barren_biome_generation_dead_chance`: like `mismatched_biome_generation_dead_chance` for barren biomes

- `nether_generation_stunted_chance`:  like `mismatched_biome_generation_stunted_chance` for nether
- `nether_generation_dead_chance`: like `mismatched_biome_generation_dead_chance` for nether

- `end_generation_stunted_chance`:  like `mismatched_biome_generation_stunted_chance` for end
- `end_generation_dead_chance`: like `mismatched_biome_generation_dead_chance` for end

**Comment by yurisuika** [comment]
Hi, the mod is open source; the master branch is just used as a front-end for the repository.

I do like your suggestions. I threw in the Nether and End stuff at the last minute, but adding configurability for that was already planned for an update you'll be happy to know!

Configurability for the chance is another good idea. Seeing that on the Fabric Wiki tutorial for trees did plant that seed in my head as well. I am a novice at the moment, but I will try to redo the mod with your suggestions.

**Comment by supersaiyansubtlety** [comment]
Oh oops, should have checked the branches.

Looking forward to future updates!

**Comment by supersaiyansubtlety** [comment]
Thanks for 1.1.0!

Note that the new configs didn't generate in the config json until I deleted the old config.

**Comment by yurisuika** [comment]
Alright I have implemented most of this. I want to consider how to approach the "barren" biome part in a different way as to not make the config and code so large. I might just make it a kind of modifier like the Endemic one. Otherwise, version 1.1.0 is very much like this.
