### ISSUE TITLE
[Request] Option to require a path to the sky for saplings to grow

### ISSUE THREAD

**Issue by AeiouEnigma** [yurisuika/Endemic#3]
Mostly to be able to prevent trees from being grown in underground farms, which some folks might desire.

**Comment by supersaiyansubtlety** [comment]
I see what you're getting at but:
- random tick growth already requires light (sky light? I forget)
- most tree farms need to prevent random tick growth by having a ceiling so trees don't grow at the wrong time and break the machine

So this option would (possibly unintentionally) nerf tree farms *a lot*.

**Comment by yurisuika** [comment]
Not a bad idea. If skylight is less than 1, you could put a chance to whether they should grow.

**Comment by yurisuika** [comment]
The way I see it, if you don't want trees to be grown in a cave or inside a building, then you probably aren't going to be making a tree farm without skylight. So, turn it up to 100 chance if you want it normal, 0 for totally off, anywhere in-between to slow down the growth.

https://minecraft.fandom.com/wiki/Tree#Growth_and_characteristics

**Comment by yurisuika** [comment]
This functionality has been added for 1.2.0!
