### ISSUE TITLE
Exception ticking world

### ISSUE THREAD

**Issue by Akairilia** [yurisuika/Endemic#4]
**java.lang.IllegalArgumentException: Cannot get property class_2758{name=distance, clazz=class java.lang.Integer, values=[1, 2, 3, 4, 5, 6, 7]} as it does not exist in Block{minecraft:oak_sapling}
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at net.minecraft.class_2397.handler$bin000$injectDistance(class_2397.java:521)
	at net.minecraft.class_2397.method_10302(class_2397.java:92)
	at net.minecraft.class_2397.method_9559(class_2397.java:65)
	at net.minecraft.class_4970$class_4971.method_26191(class_4970.java:953)
	at net.minecraft.class_4970$class_4971.method_26183(class_4970.java:895)
	at net.minecraft.class_1937.method_30092(class_1937.java:247)
	at net.minecraft.class_1937.method_8652(class_1937.java:198)
	at com.yurisuika.endemic.block.EndemicSaplingBlock.method_10507(EndemicSaplingBlock.java:43)
	at com.yurisuika.endemic.block.EndemicSaplingBlock.method_9514(EndemicSaplingBlock.java:36)
	at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:921)
	at net.minecraft.class_3218.method_18203(class_3218.java:483)
	at net.minecraft.class_3215.method_14161(class_3215.java:380)
	at net.minecraft.class_3215.method_12127(class_3215.java:325)
	at net.minecraft.class_3218.method_18765(class_3218.java:308)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)**

Fabric Mods: 
		accurateblockplacement: Accurate Block Placement 1.0.11
		additionaladditions: Additional Additions 3.0.1
		adorn: Adorn 3.3.1+1.18.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.1
		advancementplaques: Advancement Plaques 1.4.3
		advancements-enlarger: Advancements Enlarger 0.2.4
		advdebug: Advancements Debug 2.3.0
		adventurez: AdventureZ 1.4.7
		alloy_forgery: Alloy Forgery 2.0.9+1.18
		amplified_nether: Amplified Nether for Fabric 1.0.1
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.18.1
		animatica: Animatica 0.3+1.18
		annotateddi: Annotated DI 2.0.4+1.18
		antighost: AntiGhost 1.18-fabric0.43.1-1.1.4
		anvilrestoration-fabric: Anvil Restoration (Fabric) 1.1
		aopalliance_aopalliance: aopalliance 1.0
		aqupdcaracal: Caracal mob 1.18-1.3.5.1
		aqupdgrizzly: Grizzly Bear mob 1.18-1.2.2
		arcanus: Arcanus 1.25
		architects_palette: Architect's Palette Fabric 1.3
		architectury: Architectury 3.7.20
		archon: Archon 0.1.1
		armorchroma: Armor Chroma 1.2.0
		armorsoundtweak: Armor Sound Tweak 5.0.0
		artifality: Artifality 0.5.5
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autofish: Autofish 0.9.4
		axolotlitemfix: Axolotl Item Fix 1.1.3
		balm-fabric: Balm 2.4.0+0
		bannerpp: Banner++ 2.0.4+mc.1.18-rc4
		basicshields: Basic Shields [Fabric] 1.1.1-1.18.1
		bclib: BCLib 1.3.3
		beenfo: Beenfo 1.18.1-fabric0.45.0-1.3.3
		besmirchment: Besmirchment 1.18-9
		betteranimalsplus: Better Animals Plus 1.18.1-11.0.4
		betterazalea: Better Azalea 1.0.1-SNAPSHOT
		betterbeds: Better Beds 1.2.0
		betterf3: BetterF3 1.2.2
		betterfpsdist: Better FPS distance Mod 1.18-1.5
		bettermounthud: Better Mount HUD 1.1.4
		betterpingdisplay: Better Ping Display 1.1.1
		bettersleeping: BetterSleeping 0.5.1+1.18
		betterstrongholds: YUNG's Better Strongholds 1.18.1-1.0.1
		betterthirdperson: Better Third Person 1.6.0
		bewitchment: Bewitchment 1.18-13
		biomeinfo: Biome Info 1.18-8
		biomemakeover: Biome Makeover 1.18.1-1.4.7
		blockvariants: Block Variants 1.18.1-FABRIC-0.0.2
		blossom: Blossom 1.18.1-1.0.2
		blue_endless_jankson: jankson 1.2.1
		boatcontainer: BoatContainer 1.0.4
		boatiview: Boat Item View 0.0.3
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.5-1.18
		botania: Botania 1.18.1-427-FABRIC
		bouncierbeds-fabric: Bouncier Beds (Fabric) 1.0
		bountiful: Bountiful 2.0.1
		breakprogress: Break Progress 1.0.1
		buriedbarrels: Buried Barrels 1.0.3.1
		byg: BYG 1.3.5.10
		candlestick: Candlestick 1.1.2
		capybara: Capybara 1.0.1
		cardinal-components: Cardinal Components API 4.1.3
		cardinal-components-base: Cardinal Components API (base) 4.1.3
		cardinal-components-block: Cardinal Components API (blocks) 4.1.3
		cardinal-components-chunk: Cardinal Components API (chunks) 4.1.3
		cardinal-components-entity: Cardinal Components API (entities) 4.1.3
		cardinal-components-item: Cardinal Components API (items) 4.1.3
		cardinal-components-level: Cardinal Components API (world saves) 4.1.3
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 4.1.3
		cardinal-components-world: Cardinal Components API (worlds) 4.1.3
		carrier: Carrier 1.9.1
		cauldronlib: Cauldronlib 1.2.2
		cavetweaks: Cave Tweaks 1.0
		cem: Custom Entity Models 0.7.0
		chalk: Chalk 1.2.2
		chat_heads: Chat Heads 0.6.0
		cherishedworlds: Cherished Worlds 2.0.1-1.18
		chipped: Chipped 1.2
		chisel: Chisel Refabricated 1.4.4
		cleancut: CleanCut 1.18-4.0-fabric
		cleardespawn: Clear Despawn 1.1.5
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.2.57
		cloth-config-lite: cloth-config-lite 2.0.6
		clumps: Clumps 8.0.4
		collective-fabric: Collective (Fabric) 3.14
		com_electronwill_night-config_core: core 3.6.5
		com_electronwill_night-config_toml: toml 3.6.5
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_fasterxml_jackson_dataformat_jackson-dataformat-yaml: jackson-dataformat-yaml 2.13.0
		com_google_inject_guice: guice 5.0.1
		comforts: Comforts 1.0.2-1.18.1
		companion: Companion 1.2.1
		complete_bone_meal: Complete Bone Meal 1.3.0
		connectiblechains: Connectible Chains 2.0.0
		consistency_plus: Consistency Plus 0.4.3+1.18
		continuity: Continuity 1.0.3+1.18
		controlling: Controlling For Fabric 9.0.8
		coolershields: Cooler Shields 2.4.0
		copperequipment: Copper Equipment fabric-1.18.1-v2.0.0
		crawl: Crawl 0.10.2
		creativekeybind: CreativeKeybind 1.18.1-fabric-1.0.2
		crookedcrooks: Crooked Crooks 2.0.1+1.18.1
		croparia: Croparia 3.8.2
		crops_love_rain: Crops Love Rain 1.1.0
		crowdin-translate: CrowdinTranslate 1.4+1.18
		cryingghasts-fabric: Crying Ghasts (Fabric) 1.4
		cryingportals-fabric: Crying Portals (Fabric) 1.2
		cullleaves: Cull Leaves 2.3.2
		curses: Curses 1.7.1
		cyanide: Cyanide (Fabric) 2.0.2
		cyclepaintings-fabric: Cycle Paintings (Fabric) 2.1
		damagetilt: Damage Tilt 1.18-fabric-0.1.2
		darkness: True Darkness 2.0.89
		darkwaters: Dark Waters 0.0.9
		dawn: Dawn API 3.2.0
		day_dream: Day Dream 1.0.4
		decapitation: Decapitation 2.0.0
		decorative_blocks: Decorative Blocks 2.0.2
		dehydration: Dehydration 1.2.7
		despawningeggshatch-fabric: Despawning Eggs Hatch (Fabric) 2.3
		detailab: Detail Armor Bar 2.6.1+1.18-fabric
		direbats: Direbats 2.1.0
		dragonloot: DragonLoot 1.0.10
		drippyloadingscreen: Drippy Loading Screen 1.4.2
		dtdash: Double-Tap Dash 1.0.0
		dual_riders: DualRiders 1.0.5
		dummmmmmy: MmmMmmMmmMmm 1.18-1.5.0
		dungeons_arise: When Dungeons Arise 2.1.49d-fabric
		dynmus: Dynamic Music 1.4.1
		early_buckets: Early-Game Buckets 2.0.0+1.18
		earthbounds: Earthbounds 1.0.5
		earthtojavamobs: Earth2Java 1.7.4+1.18
		easymagic: Easy Magic 3.2.1
		eatinganimationid: Eating Animation 1.5
		ec-core: Essential Commands Core 1.0.1-mc1.18.1
		edibles-fabric: Edibles (Fabric) 2.4
		eggtab: Egg Tab 2.1.0+1.16-fabric
		elytratrinket: Elytra Trinket 3.0.0-1.18.1
		enchdesc: EnchantmentDescriptions 9.0.5
		endemic: Endemic 1.18.1-1.2.0
		endgoblintraders: End Goblin Traders 1.4.2
		enhancedcelestials: Enhanced Celestials 2.0.6
		entity_texture_features: Entity Texture Features 2.1.3
		entitybanners: Entity Banners 1.0.2-BETA+1.18
		environmentz: EnvironmentZ 1.2.1
		equipmentcompare: Equipment Compare 1.2.9
		essential_commands: Essential Commands 0.20.0-mc1.18.1
		exlineawnings: Exline's Awnings 1.18
		exlinefurniture: Exline's Furniture fabric-1.18.1-v2.0.4
		explorerscompass: Explorer's Compass 1.18.1-2.0.2-fabric
		extended_armor_bars: Extended Armor Bars 1.1.0
		extendedbonemeal-fabric: Extended Bone Meal (Fabric) 1.4
		extraalchemy: Extra Alchemy 1.7.0
		extrasounds: Extra Sounds 2.2.0+1.18
		extraweapons: Consulars Extra Weapons & Armor 1.0.0
		fabric: Fabric API 0.46.4+1.18
		fabric-api-base: Fabric API Base 0.4.2+d7c144a865
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.3+d7c144a865
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a865
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.10+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a865
		fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a865
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.8+d7c144a865
		fabric-copper-golem: Copper Golem 1.0.3+1.18
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a865
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a865
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a865
		fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.6+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.9+d7c144a865
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.7+b4f4f6cd65
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.13+713c266865
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a865
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.6+d7c144a865
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.11+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.4+d7c144a865
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a865
		fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.4+d7c144a865
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.12+d7c144a865
		fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac65
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.11+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.15+6825030165
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+713c266865
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.14+713c266865
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.8+d7c144a865
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a865
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.3+d7c144a865
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.8+d7c144a865
		fabric-textures-v0: Fabric Textures (v0) 1.0.10+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.8+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.9+d7c144a865
		fabric-tree-chopper: Fabric Tree Chopper 0.8.4
		fabrication: Fabrication 2.3.0_01
		fabricloader: Fabric Loader 0.13.1
		fabricshieldlib: Fabric Shield Lib 1.4.5-1.18
		fallingleaves: Falling Leaves 1.9.0+1.18.1
		fallthroughslime-fabric: Fall Through Slime (Fabric) 1.4
		fancymenu: FancyMenu 2.4.3
		farmersdelight: Farmer's Delight 1.18.1-0.2.0
		fastfurnace: FastFurnace 1.18-4
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 1.0.1+1.18.1
		ferritecore: FerriteCore 4.0.0
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.2.0
		fireplacelib: Fireplace Lib 6.2.2+1.18
		firespreadtweaks-fabric: Fire Spread Tweaks (Fabric) 1.2
		fireworkfrenzy: Firework Frenzy 1.7
		firstjoinmessage-fabric: First Join Message (Fabric) 1.3
		firstperson: FirstpersonModel 2.1.0
		fishofthieves: Fish of Thieves 1.0.0
		fixedwaterlogging: Fixed Waterlogging 1.0.2
		flonters: Flonters 1.3.0+1.18.1
		foodplusid: Food+ 1.3.1
		forgeconfigapiport: Forge Config API Port 3.1.0
		fortune-gives-experience: Fortune Gives Experience 1.1.0
		friendsandfoes: Friends&Foes 1.2.4
		furnacerecycle-fabric: Furnace Recycle (Fabric) 1.0
		gateofbabylon: Gate Of Babylon 1.6.0-1.18.1
		gbfabrictools: GBfabrictools 1.3.4+1.18
		geckolib3: Geckolib 3.0.32
		gemsandcrystals: Gems and Crystals Mod Fabric-1.18.1-1.0.0
		geodes: More Geodes 1.2.0
		glassdoor: Glass Doors 2.1.0+1.18
		gobber2: Gobber2 2.5.62
		goblintraders: Goblin Traders 1.5
		goosik-config: goosik-config 0.2.0
		graveyard: The Graveyard 1.5
		greater_eye: Greater Eye of Ender 1.3.21
		grindenchantments: Grind Enchantments 1.5.0+1.18
		guardiansgalore: GuardiansGalore 1.18-3.0
		guardvillagers: Guard Villagers Fabric 1.0.7
		guild: Guild 0.3.6
		handoveryouritems-fabric: Hand Over Your Items (Fabric) 1.3
		harvest_scythes: Harvest Scythes 2.4.0
		health_levels: Health Levels 1.0.2
		hellocrosshair: Hellocrosshair 1.0.4
		herdspanic: Herds Panic 1.0.4
		highlighter: Highlighter 1.1.2
		homebodies_fantasy: Homebodies: Fantasy 1.0.0
		horse_gear_recipes: Horse Gear Recipes 1.0.0
		horseinboat: HorseInBoat fabric-1.1.1
		huskspawn-fabric: Husk Spawn (Fabric) 1.4
		hyperlighting: Hyper Lighting 1.0.1
		iceberg: Iceberg 1.0.38
		icepreventscropgrowth-fabric: Ice Prevents Crop Growth (Fabric) 1.4
		illuminations: Illuminations 1.10.2
		immersive_weathering: Immersive Weathering 2.0.1
		impactfulweather: Impactful Weather 1.21
		impaled: Impaled 1.0.2
		impersonate: Impersonate 2.4.0
		improved-stations: Improved Stations 2.0.8
		incantationem: Incantationem 1.1.3+1.18.1
		indium: Indium 1.0.2-alpha2+mc1.18.1
		infinitetrading-fabric: Infinite Trading (Fabric) 2.1
		inmis: Inmis 2.5.1-1.18.1
		inspecio: Inspecio 1.2.1+1.18
		inventoryhud: Inventory HUD + 3.4.2
		inventoryprofilesnext: Inventory Profiles Next 1.3.3
		iris: Iris 1.2.0-pre
		itemborders: Item Borders 1.1.5
		itemmodelfix: Item Model Fix 1.0.3+1.18
		jankson: Jankson 4.0.0+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 17
		javax_inject_javax_inject: javax.inject 1
		jumpoverfences: JumpOverFences 1.16-0.0.3
		kambrik: Kambrik 3.0.0
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		keepmysoiltilled-fabric: Keep My Soil Tilled (Fabric) 1.0
		kelpfertilizer-fabric: Kelp Fertilizer (Fabric) 1.8
		kirin: Kirin UI 1.10.0-beta.2
		kiwi: Kiwi 5.2.2
		konkrete: Konkrete 1.3.3
		lambdabettergrass: LambdaBetterGrass 1.2.2+1.17
		lambdynlights: LambDynamicLights 2.1.0+1.17
		lanserverproperties: Lan Server Properties 1.7
		lazydfu: LazyDFU 0.1.2
		legendarytooltips: Legendary Tooltips 1.2.4
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 5.1.0+1.18
		libninepatch: LibNinePatch 1.1.0
		llamarama: Llamarama 1.5.3
		lovely_snails: Lovely Snails 1.0.3+1.18
		lushforest: Lush Forests 1.2.0
		lychee: Lychee Tweaker 1.5.1
		maelstrom_library: Maelstrom Library 1.2.3-1.18-rc3
		magna: Magna 1.7.0-1.18-pre1
		mambience: MAmbience 4.0.3+1.18.1
		marihuana: MoreAchievements 1.0.4
		maybe-data: Maybe data 1.0.1-1.17
		mbembe: Mbembe 1.0.2
		mcdict: MCDict 2.1.0+1.17.1
		mcwfences: Macaw's Fences and Walls 1.0.4
		mcwlights: Macaw's Lights and Lamps 1.0.2
		mcwpaintings: Macaw's Paintings 1.0.2
		mcwtrpdoors: Macaw's Trapdoors 1.0.4
		me_hypherionmc_night-config_core: core 3.6.5_custom
		me_hypherionmc_night-config_toml: toml 3.6.5_custom
		medievalweapons: Medieval Weapons 1.1.7
		megane: megane 7.0.2
		megane-api: megane-api 7.0.0
		megane-fabric-transfer: megane-fabric-transfer 7.0.0
		megane-runtime: megane-runtime 7.0.0
		megane-vanilla: megane-vanilla 7.0.0
		megaparrot: Megaparrot 1.0.2
		mermod: Mermod 1.9
		midnightlib: MidnightLib 0.3.1
		milkallthemobs-fabric: Milk All The Mobs (Fabric) 1.6
		milkevsessentials: Milkevs Essentials 1.5.0
		minecraft: Minecraft 1.18.1
		mineralchance-fabric: Mineral Chance (Fabric) 1.6
		mm: Manningham Mills 2.3
		mobs_attempt_parkour: Mobs Attempt Parkour 0.2.4-1.18
		mobscarecrow: Mob Scarecrow 1.1.0
		modid: Example Mod 3.0.1.0
		modmenu: Mod Menu 3.0.1
		mooshroomspawn-fabric: Mooshroom Spawn (Fabric) 1.5
		mooshroomtweaks-fabric: Mooshroom Tweaks (Fabric) 1.6
		more-axolotls: More Axolotls 1.0.2
		more_gems: More Gems 1.3.58
		morebannerfeatures: More Banner Features 1.1.3
		moretags: More Tags 2.0.3
		morevillagers-fabric: MoreVillagersFabric 3.1.0-SNAPSHOT
		mostructures: Mo' Structures 1.3.0-pre1+1.18
		mousetweaks: Mouse Tweaks 2.20
		multipart_entities: MultipartEntities 1.1.4-1.18-rc3
		mythic-mounts: Mythic Mounts 1.18-4.0
		namepain: Name Pain 1.4.0
		naturescompass: Nature's Compass 1.18.1-2.0.2-fabric
		netherportalspread-fabric: Nether Portal Spread (Fabric) 5.6
		nicemod: NiceMod - New blocks 0.1.7.1
		nimble: Nimble 2.2.0
		no_null_processors: No Null Processors - Fabric 2.0.1+1.18.1
		noanglebrackets: NoAngleBrackets 1.1.0
		noenchantcap: No Enchant Cap 1.18.1-fabric-2.1.1
		nohostilesaroundcampfire-fabric: No Hostiles Around Campfire (Fabric) 3.8
		nopearldamage: No Pearl Damage! 1.1.2
		notenoughanimations: NotEnoughAnimations 1.4.0
		npcvariety: NPC Variety 2.2.1
		odysseyhud: OdysseyHUD fabric-1.18.1-2.0
		omega-config: OmegaConfig 1.2.3-1.18.1
		omega-config-gui: Omega Config GUI 1.2.2-1.18.1
		onsoulfire: On Soul Fire 1.18-1
		openloader: OpenLoader 11.0.3
		orcinus: Hedgehog 1.1.3
		org_anarres_jcpp: jcpp 1.4.14
		org_apache_commons_commons-text: commons-text 1.9
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		oro_config: OroArmor Config 2.1.0
		owo: oωo 0.5.1+1.18
		oxidized: Oxidized 1.5.2
		oystersreborn: Oysters Reborn 1.1.0
		patchouli: Patchouli 1.18.1-65-FABRIC
		pehkui: Pehkui 3.1.0+1.14.4-1.18.1
		pickupnotifier: Pick Up Notifier 3.1.0
		placeholder-api: Placeholder API 1.1.3+1.17.1
		playerabilitylib: Pal 1.5.0
		pling: Pling 1.5.0
		pluckablearrows: PluckableArrows 1.1.5
		plushies: Plushie Mod 1.1
		prefab: Prefab 3.0.5
		presencefootsteps: Presence Footsteps 1.4.0
		pride: Pride Lib 1.1.0+1.17
		publicguiannouncement: Public Gui Announcement 3.1.0.3
		puddles: Puddles 1.2.0
		pugh_lib: Pugh Lib 1.2.15
		pugh_tools: Pugh Tools 1.1.17
		puzzleslib: Puzzles Lib 3.1.3
		quicksand: Quicksand 1.0.3
		quickteleports: QuickTeleports 1.18.1-1.2.0
		raised: Raised 1.18.1-1.0.2
		ratsmischief: Rat's Mischief 1.3.4
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		realisticfirespread: Realistic Fire Spread 1.18-1
		reinfbarrel: Reinforced Barrels 1.0.6+1.18
		reinfchest: Reinforced Chests 1.0.6+1.18
		reinfcore: Reinforced Core 1.1.3+1.18
		repurposed_structures: Repurposed Structures 3.3.12+1.18.1
		revamped_phantoms: Revamped Phantoms 0.2.1
		right-click-harvest: Right-Click-Harvest 1.1.0
		ringsofascension: Rings of Ascension 1.0
		rocks: This Rocks! 1.5.2
		roughlyenoughitems: Roughly Enough Items 7.3.432
		rpgdifficulty: Rpg Difficulty 1.0.8
		ruined_equipment: Ruined Equipment 1.4.0
		runelic: Runelic 10.0.1
		salem: Salem 1.1.3
		saplanting: Saplanting 1.0
		sculk_worm: Sculk Worm 0.1.5
		seasons: Fabric Seasons 1.3-BETA+1.18
		seedfix: Seed Fix 1.0.0
		shwfox: Shadew's Foxes 1.2+fabric
		skeletonhorsespawn-fabric: Skeleton Horse Spawn (Fabric) 1.9
		skinlayers: 3d Skin Layers 1.4.0
		skyvillages: Sky Villages 1.0.1-1.18.1-fabric
		slimyfloor: Slimy Floor 1.18-1.2.2
		small_artifacts: Small Artifacts 0.1.0-1.18
		smoothboot: Smooth Boot 1.18-1.7.0
		smoothswapping: Smooth Swapping 0.4.3
		snorkelmod: Snorkel Mod 1.18.1
		snowpig: Snow Pig 1.0.1
		snowrealmagic: Snow! Real Magic! 3.2.2
		soaringstructures2: Soaring Structures 2 - Clean Version 1.18.1 - 2.2
		sodium: Sodium 0.4.0-alpha6+build.14
		softdrinks: Soft Drinks 1.1.0
		someforgepatchesported: Some Forge Patches Ported 1.0.2
		sound_physics_remastered: Sound Physics Remastered 1.18.1-1.0.4
		soundcategories: Sound Categories 1.2.0+1.18
		spark: spark 1.7.2
		spidersproducewebs-fabric: Spiders Produce Webs (Fabric) 1.5
		spoornweaponattributes: SpoornWeaponAttributes 2.3
		spruceui: SpruceUI 3.3.2+1.17
		spyglass-improvements: Spyglass Improvements 1.1+mc1.18.1
		starlight: Starlight 1.0.0+fabric.d0a3220
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		stemaria: Stemaria 1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stonecutter_recipe_tags: Stonecutter Recipe Tags 2.0.0
		stoneholm: Stoneholm 1.4.2
		strayspawn-fabric: Stray Spawn (Fabric) 1.5
		subterrestrial: Subterrestrial 1.0.1
		superflatworldnoslimes-fabric: Superflat World No Slimes (Fabric) 1.5
		talkbubbles: Talk Bubbles 1.0.1
		tawct: Time & Wind Custom Ticker 1.4.2+1.18
		terrablender: TerraBlender 1.1.0.77
		terraform-shapes-api-v1: Terraform Shapes API (v1) 2.1.0
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		terralith: Terralith for Fabric 2.0.12
		terrarianslimes: Terrarian Slimes 1.1-BETA+1.18
		thatched: Thatched 1.0.1
		things: Things 0.2.14+1.18
		third_person_maps: Third Person Maps 1.3.0
		thonkutil: ThonkUtil 2.6.0+1.18
		thonkutil-base: ThonkUtil Base 1.5.1+31ad4eb1c8
		thonkutil-capes-v1: ThonkUtil Capes (v1) 1.2.2+befce073c8
		thonkutil-coords-v1: ThonkUtil Coords (v1) 1.0.6+6a7a08aec8
		thonkutil-customization: ThonkUtil Customization (v1) 1.0.1+6a7a08aec8
		thonkutil-legacy: ThonkUtil Legacy 1.0.7+6fa117f8c8
		thonkutil-potions-v0: ThonkUtil Potions (v0) 1.3.1+befce073c8
		thonkutil-trades-v1: ThonkUtil Trades (v1) 1.1.8+d77526a2c8
		timeoutout: TimeOut Out 1.0.0+1.18
		tinyskeletons: Tiny Skeletons 3.1.0
		toolstats: ToolStats 8.0.1
		tooltipfix: ToolTip Fix 1.0.4-1.18
		totw_additions: Towers of the Wild: Additions 1.1.0
		towers_of_the_wild_reworked: Towers of the Wild: Reworked 2.1.1
		transcendingtrident-fabric: Transcending Trident (Fabric) 2.2
		transportables: Transportables 1.1
		treehollows: Tree Hollows 1.0
		trinketofundying: Trinket of Undying 2.0.1-1.18
		trinkets: Trinkets 3.1.0
		twigs: Twigs 1.1.2
		twm: The Wild Mod 0.5
		unearthed: Unearthed 2.2.0
		unforgivingvoid: Unforgiving Void 3.1.1+1.18
		universal_ores: Universal Ores 1.2.1
		unvotedandshelved: Unvoted & Shelved 1.0.4
		valley: ValleyCraft 2.2.2-1.18.1
		vanilla-hammers: Vanilla Hammers 3.2.0-1.18.1
		vanillaexcavators: Vanilla Excavators 1.1.0
		villagernames: Villager Names 3.0.1
		visuality: Visuality 0.4.1
		visualoverhaul: VisualOverhaul 4.0.0
		visualworkbench: Visual Workbench 3.1.0
		voidz: VoidZ 1.0.5
		waterdripsound: Drip Sounds 1.18-0.3.0
		waveycapes: WaveyCapes 1.0.4
		waystones: Waystones 2.4.1
		weakerspiderwebs-fabric: Weaker Spiderwebs (Fabric) 2.0
		wildlife: Wildlife 1.18-1.0
		windchimes: Windchimes 1.2.0
		winterly: Winterly 0.5.1
		wmitaf: WMITAF 2.2.0
		wthit: wthit 4.4.0
		xaerominimap: Xaero's Minimap 22.1.1
		xaeroworldmap: Xaero's World Map 1.20.1
		xlpackets: XLPackets 2.1-1.17.1
		yigd: You're in Grave Danger 1.2.14
		yosbr: YOSBR 0.1.1
		yungsapi: YUNG's API 1.18-Fabric-36
		zombiehorsespawn-fabric: Zombie Horse Spawn (Fabric) 3.0

**Comment by yurisuika** [comment]
Thanks for the report, but this is actually an issue with Blossom, not Endemic.

See this for the issue:
https://github.com/yurisuika/Blossom/issues/2
